image: mcr.microsoft.com/dotnet/sdk:7.0

pages:
  stage: deploy
  script:
    - cd SkyColors
    - dotnet publish -c Release -o output 
    - cd ../
    - cp -a -r ./SkyColors/output/wwwroot ./public
  artifacts:
    paths:
      - public
  only:
  - main
