name: Build and deploy to Gitlab Pages

on: [push]

jobs:
  build:
    name: build using
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.400
    
      - name: Build with dotnet
        run: dotnet build -c Release -o output
      
      - name: deploy to Gitlab Pages
        run: cp -a -r ./SkyColors/output/wwwroot ./public
