image:  microsoft/dotnet:2.1.302-sdk

before_script:
  - dotnet restore
  
pages:
  stage: deploy
  script:
  - mkdir public
  - cd ./SkyColors
  - dotnet publish -c Release -o output
  - cp -a ./SkyColors/output/SkyColors/dist/* ./public
  artifacts:
    paths:
    - public
  only:
  - main
