image:  microsoft/dotnet:7.0.302-sdk

pages:
  stage: deploy
  script:
  - mkdir public
  - cd ./SkyColors
  - cp -a ./output/wwwroot/* ../public
  artifacts:
    paths:
    - public
  only:
  - main
