image:  microsoft/dotnet:7.0.302-sdk

pages:
  stage: deploy
  script:
  - cd ./SkyColors
  - cp -a -r ./output/wwwroot ../
  - mv wwwroot public
  artifacts:
    paths:
    - public
  only:
  - main
