image:  microsoft/dotnet:7.0.302-sdk

before_script:
  - cd ./SkyColors
  - dotnet restore
  - cd ../
  
pages:
  stage: deploy
  script:
  - mkdir public
  - cd ./SkyColors
  - dotnet publish -c Release -o output
  - cp -a ./SkyColors/output/wwwroot/* ./public
  artifacts:
    paths:
    - public
  only:
  - main
